[local]
localhost

[mongodb]
mongodb.qkeats.shop

[redis]
redis.qkeats.shop

[mysql]
mysql.qkeats.shop

[rabbitmq]
rabbitmq.qkeats.shop

[catalogue]
catalogue.qkeats.shop

[user]
user.qkeats.shop

[cart]
cart.qkeats.shop

[shipping]
shipping.qkeats.shop

[payment]
payment.qkeats.shop

[frontend]
frontend.qkeats.shop

[private-key-demo]
172.31.37.172